["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "."

["protostar.contracts"]
Storage=[
    "./exercises/contracts/storage/storage.cairo",
]
Ownable=[
    "./cairo_contracts/src/openzeppelin/access/ownable/library.cairo",
]
