["protostar.config"]
protostar_version = "0.7.0"

["protostar.project"]
libs_path = "."

["protostar.contracts"]
Storage=[
    "./exercises/contracts/storage/storage.cairo",
]
Ownable=[
    "./openzeppelin/access/ownable.cairo",
]
Consortium=[
    "./exercises/contracts/consortium/consortium.cairo",
]